export const ROUTE_OPTIONS = [
  "Oral",
  "IV",
  "IM",
  "Subcutaneous",
  "Topical",
  "Sublingual",
  "Inhalation",
  "Rectal",
  "Ophthalmic",
  "Otic",
  "Transdermal",
];
export const DOSAGE_OPTIONS = ["5mg", "10mg", "25mg", "50mg", "100mg", "250mg", "500mg", "1g"];
export const FREQUENCY_OPTIONS = ["Once daily", "Twice daily", "Three times daily", "Four times daily", "As needed"];
export const TIMING_OPTIONS = ["Before meal", "After meal", "With food", "Empty stomach", "Bedtime"];
export const DURATION_OPTIONS = ["3 days", "5 days", "7 days", "10 days", "14 days", "1 month", "2 months", "3 months"];
export const REFILL_OPTIONS = ["0", "1", "2", "3", "5", "PRN"];

export const COMMON_MEDICINES = [
  { name: "Paracetamol 500mg", category: "Fever & Pain" },
  { name: "Paracetamol 650mg", category: "Fever & Pain" },
  { name: "Ibuprofen 400mg", category: "Fever & Pain" },
  { name: "Ibuprofen 600mg", category: "Fever & Pain" },
  { name: "Aspirin 325mg", category: "Fever & Pain" },
  { name: "Naproxen 250mg", category: "Fever & Pain" },
  { name: "Caffeine + Paracetamol", category: "Headache" },
  { name: "Sumatriptan 50mg", category: "Headache" },
  { name: "Betahistine 16mg", category: "Headache" },
  { name: "Metaxalone 400mg", category: "Body Pain" },
  { name: "Chlorzoxazone 250mg", category: "Body Pain" },
  { name: "Diclofenac Gel", category: "Body Pain" },
  { name: "Volini Gel", category: "Body Pain" },
  { name: "L-Cetizine 5mg", category: "Viral Fever" },
  { name: "Cetirizine 10mg", category: "Viral Fever" },
  { name: "Montelukast 10mg", category: "Viral Fever" },
  { name: "Ambroxol 30mg", category: "Viral Fever" },
  { name: "Levocetirizine 5mg", category: "Viral Fever" },
  { name: "Cetirizine + Phenylephrine", category: "Cold & Cough" },
  { name: "Phenylephrine 10mg", category: "Cold & Cough" },
  { name: "Phenyramidol 50mg", category: "Cold & Cough" },
  { name: "Chlorpheniramine 4mg", category: "Cold & Cough" },
  { name: "Diphenhydramine 25mg", category: "Cold & Cough" },
  { name: "Azithromycin 500mg", category: "Antibiotics" },
  { name: "Amoxicillin 500mg", category: "Antibiotics" },
  { name: "Ciprofloxacin 500mg", category: "Antibiotics" },
  { name: "Ofloxacin 200mg", category: "Antibiotics" },
  { name: "Metronidazole 400mg", category: "Antibiotics" },
  { name: "Doxycycline 100mg", category: "Antibiotics" },
  { name: "Pantoprazole 40mg", category: "Stomach" },
  { name: "Omeprazole 20mg", category: "Stomach" },
  { name: "Domperidone 10mg", category: "Stomach" },
  { name: "Ondansetron 4mg", category: "Stomach" },
  { name: "Ranitidine 150mg", category: "Stomach" },
  { name: "Polycrol Suspension", category: "Stomach" },
  { name: "Amlodipine 5mg", category: "BP & Heart" },
  { name: "Amlodipine 10mg", category: "BP & Heart" },
  { name: "Metoprolol 25mg", category: "BP & Heart" },
  { name: "Atenolol 50mg", category: "BP & Heart" },
  { name: "Losartan 50mg", category: "BP & Heart" },
  { name: "Metformin 500mg", category: "Diabetes" },
  { name: "Metformin 1000mg", category: "Diabetes" },
  { name: "Glimepride 2mg", category: "Diabetes" },
  { name: "Glimepride 4mg", category: "Diabetes" },
  { name: "Vitamin B-Complex", category: "Vitamins" },
  { name: "Vitamin C 500mg", category: "Vitamins" },
  { name: "Vitamin D3 1000IU", category: "Vitamins" },
  { name: "Calcium + Vitamin D", category: "Vitamins" },
  { name: "Iron + Folic Acid", category: "Vitamins" },
  { name: "Miconazole Cream", category: "Skin" },
  { name: "Clindamycin Gel", category: "Skin" },
  { name: "Fusidic Acid Cream", category: "Skin" },
  { name: "Hydrocortisone Cream", category: "Skin" },
];
